name: Reusable Deploy
on: workflow_call # Este workflow se ejecutara cuando se llame desde otros workflows
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output information from other workflow
        run: echo "Deploying and uploading"