name: Reusable Deploy
on: 
  workflow_call: # Este workflow se ejecutara cuando se llame desde otros workflows
    inputs: # Indicamos que espera recibir este workflow
      artifact-name: # Nombre que le daremos a lo que recibe para identificarlo
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
    # Pasamos secretos
    # secrets:
    #   some-secret:
    #     required: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          # name: dist-files
          name: ${{ inputs.artifact-name }} # Rescatamos el valor que recibimos con el nombre que le dimos
      - name: List files
        run: ls
      - name: Output information from other workflow
        run: echo "Deploying and uploading"